[package]
name = "d2k_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
d2k_errors = { path = "../d2k_errors" }
d2k_lexer = { path = "../d2k_lexer" }
codespan-reporting = { workspace = true }
thiserror = "2.0.17"
