[package]
name = "d2k_events"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = { workspace = true }
itertools = "0.14.0"
lcf = { workspace = true }
ron = "0.11.0"
serde = { workspace = true }
